"""Framework adapters — generate config files for different agent frameworks.

Clean-room implementations. No code from OpenClaw or Hermes Agent.
See DEVELOPMENT_DOCUMENT.md Appendix D.
"""

import json
from dataclasses import dataclass, field


@dataclass
class GeneratedFile:
    filename: str
    content: str
    description: str


FOOTER = "\n\n---\n*Generated by [Debriefeur](https://github.com/aigenteur/debriefeur)*\n"


def generate_openclaw(knowledge: dict) -> list[GeneratedFile]:
    """Generate .openclaw/ directory files."""
    files = []

    # soul.md
    soul = ["# Role\n\nProfessional assistant operating by the decision frameworks below.\n"]
    soul.append("\n# Core Mission\n\nExecute tasks with the same judgment as your principal. Never guess — ask when uncertain.\n")
    for fw in knowledge.get("recurring_decisions", {}).get("decision_frameworks", []):
        if isinstance(fw, dict):
            soul.append(f"\n## {fw.get('name', 'Framework')}\n")
            soul.append(f"- **Trigger:** {fw.get('trigger', 'N/A')}\n")
            soul.append(f"- **Criteria:** {fw.get('criteria', 'N/A')}\n")
            soul.append(f"- **Default:** {fw.get('default_action', 'N/A')}\n")
            soul.append(f"- **Escalate when:** {fw.get('escalation_trigger', 'N/A')}\n")
    files.append(GeneratedFile(".openclaw/soul.md", "".join(soul) + FOOTER, "Core identity and decision frameworks"))

    # user.md
    user = ["# Schedule & Energy\n\n"]
    energy = knowledge.get("operating_rhythms", {}).get("energy_map", {})
    if isinstance(energy, dict):
        user.append(f"- **Peak hours:** {energy.get('peak_hours', 'Not specified')}\n")
        user.append(f"- **Low hours:** {energy.get('low_hours', 'Not specified')}\n")
        user.append(f"- **Deep work:** {energy.get('deep_work_blocks', 'Not specified')}\n")
    files.append(GeneratedFile(".openclaw/user.md", "".join(user) + FOOTER, "User schedule and preferences"))

    # heartbeat.md
    hb = ["# Weekly Patterns\n\n"]
    for p in knowledge.get("operating_rhythms", {}).get("weekly_patterns", []):
        if isinstance(p, dict):
            hb.append(f"## {p.get('day_of_week', '')}\n**Theme:** {p.get('theme', '')}\n")
            for a in p.get("key_activities", []):
                hb.append(f"- {a}\n")
            hb.append("\n")
    files.append(GeneratedFile(".openclaw/heartbeat.md", "".join(hb) + FOOTER, "Recurring rhythms and tasks"))

    return files


def generate_hermes(knowledge: dict) -> list[GeneratedFile]:
    """Generate Hermes Agent config files."""
    files = []

    # system_prompt.md
    sp = ["# Role\n\nSkilled professional assistant with the same judgment as your principal.\n"]
    sp.append("\n# Mission\n\nExecute delegated tasks independently when patterns are clear. Escalate when uncertain.\n")
    sp.append("\n# Boundaries\n\n- Never commit resources without approval\n- Never share sensitive data\n- Flag ambiguity instead of guessing\n")
    files.append(GeneratedFile("system_prompt.md", "".join(sp) + FOOTER, "Main system prompt"))

    # context.json
    ctx = {
        "schedule": knowledge.get("operating_rhythms", {}),
        "decisions": knowledge.get("recurring_decisions", {}),
        "tools": knowledge.get("dependencies", {}),
        "_meta": {"generated_by": "Debriefeur"},
    }
    files.append(GeneratedFile("context.json", json.dumps(ctx, indent=2, default=str), "Structured user context"))

    return files


def generate_generic(knowledge: dict) -> list[GeneratedFile]:
    """Generate generic Markdown + JSON export."""
    files = []
    files.append(GeneratedFile("knowledge_export.json", json.dumps(knowledge, indent=2, default=str), "Complete knowledge export"))

    # Human-readable summary
    md = ["# Agent Briefing Document\n\n"]
    sections = {
        "operating_rhythms": "Operating Rhythms",
        "recurring_decisions": "Recurring Decisions",
        "dependencies": "Dependencies & Tools",
        "friction_points": "Friction Points",
        "leverage_opportunities": "Leverage Opportunities",
    }
    for key, title in sections.items():
        data = knowledge.get(key)
        if data and isinstance(data, dict):
            md.append(f"## {title}\n\n")
            for sk, sv in data.items():
                md.append(f"### {sk.replace('_',' ').title()}\n\n")
                if isinstance(sv, list):
                    for item in sv:
                        if isinstance(item, dict):
                            for k, v in item.items():
                                md.append(f"- **{k}:** {v}\n")
                        else:
                            md.append(f"- {item}\n")
                elif isinstance(sv, dict):
                    for k, v in sv.items():
                        md.append(f"- **{k}:** {v}\n")
                md.append("\n")
    files.append(GeneratedFile("agent_brief.md", "".join(md) + FOOTER, "Human-readable briefing"))

    return files


ADAPTERS = {
    "openclaw": generate_openclaw,
    "hermes": generate_hermes,
    "generic": generate_generic,
}


def generate(framework: str, knowledge: dict) -> list[GeneratedFile]:
    """Generate config files for the specified framework."""
    adapter = ADAPTERS.get(framework)
    if not adapter:
        raise ValueError(f"Unknown framework '{framework}'. Available: {list(ADAPTERS.keys())}")
    return adapter(knowledge)
